// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1": {
            "post": {
                "description": "Save a new purchases",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Save a new purchases",
                "parameters": [
                    {
                        "description": "Save purchase",
                        "name": "purchase",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PurchaseDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/all/{status}": {
            "get": {
                "description": "Get a all orders by status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Get a all orders by status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/binding/{orderId}": {
            "get": {
                "description": "Get binding orders by order id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-orders"
                ],
                "summary": "Get binding orders by order id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/category": {
            "put": {
                "description": "Update category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products category"
                ],
                "summary": "Update Category",
                "parameters": [
                    {
                        "description": "Create category",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            },
            "post": {
                "description": "Save product category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products category"
                ],
                "summary": "Save category",
                "parameters": [
                    {
                        "description": "Create category",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/category/{categoryName}": {
            "get": {
                "description": "Get category by category name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products category"
                ],
                "summary": "Get category by category name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category Name",
                        "name": "categoryName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CategoryDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/criteria": {
            "put": {
                "description": "Update criteria information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Update criteria",
                "parameters": [
                    {
                        "description": "Update criteria",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CriteriaDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/criteria/in/filters/{filterId}/{criteriaId}": {
            "put": {
                "description": "Update criteria information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "criteria"
                ],
                "summary": "Update criteria",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Criteria ID",
                        "name": "criteriaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/criteria/in/product/{productId}/{criteriaId}": {
            "put": {
                "description": "Update criteria information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "criteria"
                ],
                "summary": "Update criteria",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Criteria ID",
                        "name": "criteriaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/criteria/to/filters/{filterId}": {
            "post": {
                "description": "Save criteria to filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "criteria"
                ],
                "summary": "Save criteria to filter",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter Id",
                        "name": "filterId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create filter",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CriteriaDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CriteriaDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/criteria/to/products/{productId}": {
            "post": {
                "description": "Save criteria to product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "criteria"
                ],
                "summary": "Save criteria to product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product Id",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create criteria",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CriteriaDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/criteria/{criteriaId}": {
            "get": {
                "description": "Get criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "criteria"
                ],
                "summary": "Get criteria",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Criteria ID",
                        "name": "criteriaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CriteriaDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/fetch/{orderId}": {
            "get": {
                "description": "Get manager by order id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager"
                ],
                "summary": "Get manager by order id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ManagerDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/filters": {
            "put": {
                "description": "Update filters information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Update filters",
                "parameters": [
                    {
                        "description": "Update filter",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FilterDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/filters/{filterId}": {
            "get": {
                "description": "Get filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Get filters",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter ID",
                        "name": "filterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FilterDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/filters/{subcategoryName}": {
            "post": {
                "description": "Save filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Save filters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subcategory Name",
                        "name": "subcategoryName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create filter",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FilterDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FilterDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/products": {
            "put": {
                "description": "Update product information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update Product",
                "parameters": [
                    {
                        "description": "Update product",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProductDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/products/un-publish": {
            "get": {
                "description": "Get product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get product",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/products/{productId}": {
            "get": {
                "description": "Get product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/products/{productId}/{status}": {
            "delete": {
                "description": "Change status product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Change Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/products/{subcategoryName}": {
            "post": {
                "description": "Save product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Save product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category Name",
                        "name": "categoryName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create products",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ProductDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/specifications": {
            "put": {
                "description": "Update specification information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "specification"
                ],
                "summary": "Update Specification",
                "parameters": [
                    {
                        "description": "Update specification",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SpecificationDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/specifications/{productId}": {
            "post": {
                "description": "Save specification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "specification"
                ],
                "summary": "Save specification",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create products",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SpecificationDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/specifications/{specificationId}": {
            "get": {
                "description": "Get specification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "specification"
                ],
                "summary": "Get specification",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Specification ID",
                        "name": "specificationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SpecificationDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/subcategory": {
            "put": {
                "description": "Update subcategory information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subcategory"
                ],
                "summary": "Update subcategory",
                "parameters": [
                    {
                        "description": "Update subcategory",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SubcategoryDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/subcategory/{categoryName}": {
            "post": {
                "description": "Save subcategory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subcategory"
                ],
                "summary": "Save subcategory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subcategory Name",
                        "name": "subcategoryName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create subcategory",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SubcategoryDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SubcategoryDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/subcategory/{subcategoryName}": {
            "get": {
                "description": "Get subcategory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subcategory"
                ],
                "summary": "Get subcategory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subcategory Name",
                        "name": "subcategoryName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SubcategoryDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/{orderId}/{status}": {
            "put": {
                "description": "Update order by status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Update order by status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Order Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/{status}": {
            "get": {
                "description": "Get a all orders by status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Get a all orders by status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        }
    },
    "definitions": {
        "dto.CategoryDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Phone"
                },
                "subcategories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SubcategoryDto"
                    }
                }
            }
        },
        "dto.CommentDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "This is comment description"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "comment author"
                }
            }
        },
        "dto.CriteriaDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "value": {
                    "type": "string",
                    "example": "60#"
                }
            }
        },
        "dto.CustomerDto": {
            "type": "object",
            "properties": {
                "customerAddress": {
                    "type": "string",
                    "example": "Brodvey"
                },
                "customerEmail": {
                    "type": "string",
                    "example": "julvern@gmail.com"
                },
                "customerName": {
                    "type": "string",
                    "example": "Julvern"
                },
                "customerPhone": {
                    "type": "string",
                    "example": "+780466869"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "purchaseId": {
                    "type": "integer",
                    "example": 11
                }
            }
        },
        "dto.DeliveryDto": {
            "type": "object",
            "properties": {
                "branchAddress": {
                    "type": "string",
                    "example": "189 street"
                },
                "companyName": {
                    "type": "string",
                    "example": "NowaPoshta"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "type": "string",
                    "example": "home"
                }
            }
        },
        "dto.FilterDto": {
            "type": "object",
            "properties": {
                "criteria": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CriteriaDto"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "filter_title"
                }
            }
        },
        "dto.ManagerDto": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string",
                    "example": "Michal"
                },
                "lastName": {
                    "type": "string",
                    "example": "Mackonagen"
                }
            }
        },
        "dto.OrderDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1.99
                },
                "customer": {
                    "$ref": "#/definitions/dto.CustomerDto"
                },
                "delivery": {
                    "$ref": "#/definitions/dto.DeliveryDto"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "product": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProductDto"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "status"
                }
            }
        },
        "dto.ProductDto": {
            "type": "object",
            "properties": {
                "brandName": {
                    "type": "string",
                    "example": "IPhone"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CommentDto"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "This is phone"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Phone"
                },
                "previewImage": {
                    "type": "string",
                    "example": "image"
                },
                "price": {
                    "type": "number",
                    "example": 1.11
                },
                "quantity": {
                    "type": "integer",
                    "example": 10
                },
                "specifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SpecificationDto"
                    }
                },
                "subcategoryName": {
                    "type": "string",
                    "example": "phone"
                }
            }
        },
        "dto.PurchaseDto": {
            "type": "object",
            "properties": {
                "orderId": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "open or close"
                }
            }
        },
        "dto.SpecificationDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "supper sensor"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "settings"
                }
            }
        },
        "dto.SubcategoryDto": {
            "type": "object",
            "properties": {
                "filters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FilterDto"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Phone"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Managers API",
	Description: "This is a sample service for managers",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
