// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1": {
            "post": {
                "description": "Save a new purchases",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Save a new purchases",
                "parameters": [
                    {
                        "description": "Save purchase",
                        "name": "purchase",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PurchaseDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/all/{status}": {
            "get": {
                "description": "Get a all orders by status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Get a all orders by status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/binding/{orderId}": {
            "get": {
                "description": "Get binding orders by order id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-orders"
                ],
                "summary": "Get binding orders by order id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/fetch/{orderId}": {
            "get": {
                "description": "Get manager by order id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager"
                ],
                "summary": "Get manager by order id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ManagerDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        },
        "/v1/{orderId}/{status}": {
            "put": {
                "description": "Update order by status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Update order by status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Order Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "403": {},
                    "404": {}
                }
            }
        },
        "/v1/{status}": {
            "get": {
                "description": "Get a all orders by status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchases"
                ],
                "summary": "Get a all orders by status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order Status",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.OrderDto"
                        }
                    },
                    "400": {},
                    "403": {}
                }
            }
        }
    },
    "definitions": {
        "dto.CustomerDto": {
            "type": "object",
            "properties": {
                "customerAddress": {
                    "type": "string",
                    "example": "Brodvey"
                },
                "customerEmail": {
                    "type": "string",
                    "example": "julvern@gmail.com"
                },
                "customerName": {
                    "type": "string",
                    "example": "Julvern"
                },
                "customerPhone": {
                    "type": "string",
                    "example": "+780466869"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "purchaseId": {
                    "type": "integer",
                    "example": 11
                }
            }
        },
        "dto.ManagerDto": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string",
                    "example": "Michal"
                },
                "lastName": {
                    "type": "string",
                    "example": "Mackonagen"
                }
            }
        },
        "dto.OrderDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1.99
                },
                "customer": {
                    "$ref": "#/definitions/dto.CustomerDto"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "product": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProductDto"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "status"
                }
            }
        },
        "dto.ProductDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "This is phone"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Phone"
                },
                "previewImage": {
                    "type": "string",
                    "example": "image"
                },
                "price": {
                    "type": "number",
                    "example": 1.11
                },
                "quantity": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "dto.PurchaseDto": {
            "type": "object",
            "properties": {
                "orderId": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "open or close"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8887",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Managers API",
	Description: "This is a sample service for managers",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
