drop table if exists public.brands CASCADE;
drop table if exists public.categories CASCADE;
drop table if exists public.comment CASCADE;
drop table if exists public.criteria CASCADE;
drop table if exists public.filters CASCADE;
drop table if exists public.product_stock_registration CASCADE;
drop table if exists public.products CASCADE;
drop table if exists public.specification CASCADE;
drop table if exists public.stock_staffs CASCADE;
drop table if exists public.stocks CASCADE;
drop table if exists public.subcategories CASCADE;
drop table if exists product_images CASCADE;
drop table if exists products_criteria CASCADE;
drop table if exists stock_staff_phone CASCADE;

create table public.brands
(
    id        bigint generated by default as identity,
    create_at timestamp    not null,
    name      varchar(100) not null,
    status    varchar(255),
    update_at timestamp    not null,
    primary key (id)
);

create table public.categories
(
    id        bigint generated by default as identity,
    create_at timestamp   not null,
    name      varchar(50) not null,
    status    varchar(255),
    update_at timestamp   not null,
    primary key (id)
);

create table public.comment
(
    id         bigint generated by default as identity,
    create_at  timestamp    not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    status     varchar(255),
    text       varchar(255) not null,
    update_at  timestamp    not null,
    user_id    binary       not null,
    product_id bigint,
    primary key (id)
);

create table public.criteria
(
    id          bigint generated by default as identity,
    create_at   timestamp    not null,
    status      varchar(255),
    update_at   timestamp    not null,
    value       varchar(100) not null,
    criteria_id bigint,
    primary key (id)
);

create table public.filters
(
    id             bigint generated by default as identity,
    create_at      timestamp   not null,
    status         varchar(255),
    title          varchar(50) not null,
    update_at      timestamp   not null,
    subcategory_id bigint      not null,
    primary key (id)
);

create table public.product_stock_registration
(
    id         bigint generated by default as identity,
    create_at  timestamp not null,
    quantity   integer   not null,
    update_at  timestamp not null,
    product_id bigint,
    stock_id   bigint,
    primary key (id)
);

create table public.products
(
    id             bigint generated by default as identity,
    bought_count   integer      not null,
    create_at      timestamp    not null,
    description    varchar(255) not null,
    name           varchar(100) not null,
    preview_image  varchar(255) not null,
    price          DECIMAL(8, 3),
    update_at      timestamp    not null,
    status         varchar(255),
    brand_id       bigint       not null,
    subcategory_id bigint       not null,
    primary key (id)
);

create table public.specification
(
    id          bigint generated by default as identity,
    create_at   timestamp    not null,
    description varchar(255) not null,
    name        varchar(50)  not null,
    status      varchar(255),
    update_at   timestamp    not null,
    product_id  bigint       not null,
    primary key (id)
);

create table public.stock_staffs
(
    id         bigint generated by default as identity,
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    stock_id   bigint,
    primary key (id)
);

create table public.stocks
(
    id            bigint generated by default as identity,
    city          varchar(255) not null,
    country       varchar(255) not null,
    create_at     timestamp    not null,
    email         varchar(255) not null,
    name          varchar(255) not null,
    number        varchar(255) not null,
    phone         varchar(255) not null,
    region        varchar(255) not null,
    status        varchar(255),
    street        varchar(255) not null,
    street_number varchar(255) not null,
    update_at     timestamp    not null,
    zip_code      varchar(255) not null,
    primary key (id)
);

create table public.subcategories
(
    id          bigint generated by default as identity,
    create_at   timestamp   not null,
    name        varchar(50) not null,
    status      varchar(255),
    update_at   timestamp   not null,
    category_id bigint      not null,
    primary key (id)
);

-- create
-- index public.brand_name_idx on public.brands (name)
-- alter table public.brands
--     add constraint uk_brands_name unique (name);

-- create
-- index public.category_name_idx on public.categories (name)
-- alter table public.categories
--     add constraint uk_category_name unique (name);
--
-- create
-- index public.subcategory_name_idx on public.subcategories (name)
-- alter table public.subcategories
--     add constraint uk_subcategory_name unique (name);

create table product_images
(
    product_id bigint not null,
    images     varchar(255)
);

create table products_criteria
(
    product_id  bigint not null,
    criteria_id bigint not null,
    primary key (product_id, criteria_id)
);

create table stock_staff_phone
(
    stock_staff_id bigint not null,
    phone          varchar(255)
);

alter table public.comment
    add constraint product_comments_fk foreign key (product_id) references public.products;

alter table public.criteria
    add constraint filters_criteria_fk foreign key (criteria_id) references public.filters;

alter table public.filters
    add constraint subcategory_filter_fk foreign key (subcategory_id) references public.subcategories;

alter table public.product_stock_registration
    add constraint product_stock_fk foreign key (product_id) references public.products;

alter table public.product_stock_registration
    add constraint stock_product_fk foreign key (stock_id) references public.stocks;

alter table public.products
    add constraint products_brand_fk foreign key (brand_id) references public.brands;

alter table public.products
    add constraint products_subcategory_fk foreign key (subcategory_id) references public.subcategories;

alter table public.specification
    add constraint product_specification_fk foreign key (product_id) references public.products;

alter table public.stock_staffs
    add constraint stock_staff_fk foreign key (stock_id) references public.stocks;

alter table public.subcategories
    add constraint subcategory_category_fk foreign key (category_id) references public.categories;

alter table product_images
    add constraint images_product_fk foreign key (product_id) references public.products;

alter table products_criteria
    add constraint criteria_products_fk foreign key (criteria_id) references public.criteria;

alter table products_criteria
    add constraint products_criteria_fk foreign key (product_id) references public.products;

alter table stock_staff_phone
    add constraint stock_staff_phones_fk foreign key (stock_staff_id) references public.stock_staffs;

