alter table if exists public.comment drop constraint if exists product_comments_fk;
alter table if exists public.criteria drop constraint if exists filters_criteria_fk;
alter table if exists public.filters drop constraint if exists subcategory_filter_fk;
alter table if exists public.products drop constraint if exists products_brand_fk;
alter table if exists public.products drop constraint if exists products_subcategory_fk;
alter table if exists public.specification drop constraint if exists subcategory_filter_fk;
alter table if exists public.specification_sections drop constraint if exists product_spec_section_fk;
alter table if exists public.stock_staffs drop constraint if exists stock_staff_fk;
alter table if exists public.subcategories drop constraint if exists subcategory_category_fk;
drop table if exists public.brands cascade;
drop table if exists public.categories cascade;
drop table if exists public.comment cascade;
drop table if exists public.criteria cascade;
drop table if exists public.filters cascade;
drop table if exists public.products cascade;
drop table if exists public.specification cascade;
drop table if exists public.specification_sections cascade;
drop table if exists public.stock_staffs cascade;
drop table if exists public.stocks cascade;
drop table if exists public.subcategories cascade;
alter table if exists product_images drop constraint if exists images_product_fk;
alter table if exists products_criteria drop constraint if exists criteria_products_fk;
alter table if exists products_criteria drop constraint if exists products_criteria_fk;
alter table if exists spec_section_specifications drop constraint if exists specification_spec_section_fk;
alter table if exists spec_section_specifications drop constraint if exists spec_section_specification_fk;
alter table if exists stocks_quantity drop constraint if exists product_stock_quantity_fk
alter table if exists stocks_quantity drop constraint if exists stock_quantity_product_fk
alter table if exists stock_staff_phones drop constraint if exists stock_staff_phones_fk;
drop table if exists product_images cascade;
drop table if exists products_criteria cascade;
drop table if exists spec_section_specifications cascade;
drop table if exists stocks_quantity cascade;
drop table if exists stock_staff_phones cascade;

create table public.brands
(
    id        int8 generated by default as identity,
    create_at timestamp    not null,
    name      varchar(100) not null,
    status    varchar(255),
    update_at timestamp    not null,
    primary key (id)
)
create table public.categories
(
    id                  int8 generated by default as identity,
    create_at           timestamp    not null,
    coupon_code         varchar(150),
    discount_percent    int4,
    discount_value      DECIMAL(8, 3),
    end_date            DATE,
    end_time            TIMESTAMP,
    max_order_value     DECIMAL(8, 3),
    minimal_order_value DECIMAL(8, 3),
    start_date          DATE,
    start_time          TIMESTAMP,
    name                varchar(50)  not null,
    preview_image       varchar(255) not null,
    status              varchar(255),
    update_at           timestamp    not null,
    primary key (id)
)
create table public.comment
(
    id         int8 generated by default as identity,
    create_at  timestamp    not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    status     varchar(255),
    text       varchar(255) not null,
    update_at  timestamp    not null,
    user_id    uuid         not null,
    product_id int8,
    primary key (id)
)
create table public.criteria
(
    id          int8 generated by default as identity,
    create_at   timestamp    not null,
    status      varchar(255),
    update_at   timestamp    not null,
    value       varchar(100) not null,
    criteria_id int8,
    primary key (id)
)
create table public.filters
(
    id             int8 generated by default as identity,
    create_at      timestamp   not null,
    status         varchar(255),
    title          varchar(50) not null,
    update_at      timestamp   not null,
    subcategory_id int8        not null,
    primary key (id)
)
create table public.products
(
    id                  int8 generated by default as identity,
    bought_count        int4         not null,
    create_at           timestamp    not null,
    description         varchar(255) not null,
    name                varchar(100) not null,
    preview_image       varchar(255) not null,
    price               DECIMAL(8, 3),
    update_at           timestamp    not null,
    vin_code            varchar(255) not null,
    coupon_code         varchar(150),
    discount_percent    int4,
    discount_value      DECIMAL(8, 3),
    end_date            DATE,
    end_time            TIMESTAMP,
    max_order_value     DECIMAL(8, 3),
    minimal_order_value DECIMAL(8, 3),
    start_date          DATE,
    start_time          TIMESTAMP,
    depth               int4,
    height              int4         not null,
    title               varchar(255) not null,
    weight              int4         not null,
    width               int4         not null,
    status              varchar(255),
    brand_id            int8         not null,
    subcategory_id      int8         not null,
    primary key (id)
)
create table public.specification
(
    id             int8 generated by default as identity,
    create_at      timestamp    not null,
    description    varchar(255) not null,
    name           varchar(50)  not null,
    status         varchar(255),
    update_at      timestamp    not null,
    subcategory_id int8         not null,
    primary key (id)
)
create table public.specification_sections
(
    id         int8 generated by default as identity,
    create_at  timestamp    not null,
    title      varchar(255) not null,
    update_at  timestamp    not null,
    product_id int8         not null,
    primary key (id)
)
create table public.stock_staffs
(
    id         int8 generated by default as identity,
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    stock_id   int8,
    primary key (id)
)
create table public.stocks
(
    id            int8 generated by default as identity,
    city          varchar(255) not null,
    country       varchar(255) not null,
    create_at     timestamp    not null,
    email         varchar(255) not null,
    name          varchar(255) not null,
    number        varchar(255) not null,
    phone         varchar(255) not null,
    region        varchar(255) not null,
    status        varchar(255),
    street        varchar(255) not null,
    street_number varchar(255) not null,
    update_at     timestamp    not null,
    zip_code      varchar(255) not null,
    primary key (id)
)
create table public.subcategories
(
    id            int8 generated by default as identity,
    create_at     timestamp    not null,
    name          varchar(50)  not null,
    preview_image varchar(255) not null,
    status        varchar(255),
    update_at     timestamp    not null,
    category_id   int8         not null,
    primary key (id)
)
create index brand_name_idx on public.brands (name)
alter table if exists public.brands add constraint uk_brands_name unique (name)
create index category_name_idx on public.categories (name)
alter table if exists public.categories add constraint uk_category_name unique (name)
create index subcategory_name_idx on public.subcategories (name)
alter table if exists public.subcategories add constraint uk_subcategory_name unique (name)
create table product_images
(
    product_id int8 not null,
    images     varchar(255)
)
create table products_criteria
(
    product_id  int8 not null,
    criteria_id int8 not null,
    primary key (product_id, criteria_id)
)
create table spec_section_specifications
(
    spec_section_id  int8 not null,
    specification_id int8 not null,
    primary key (spec_section_id, specification_id)
)
create table stocks_quantity
(
    stock_id        int8 not null,
    stocks_quantity int4,
    product_id      int8 not null,
    primary key (product_id, stock_id)
)
create table stock_staff_phones
(
    stock_staff_id int8 not null,
    phones         varchar(255)
)
alter table if exists public.comment add constraint product_comments_fk foreign key (product_id) references public.products
alter table if exists public.criteria add constraint filters_criteria_fk foreign key (criteria_id) references public.filters
alter table if exists public.filters add constraint subcategory_filter_fk foreign key (subcategory_id) references public.subcategories
alter table if exists public.products add constraint products_brand_fk foreign key (brand_id) references public.brands
alter table if exists public.products add constraint products_subcategory_fk foreign key (subcategory_id) references public.subcategories
alter table if exists public.specification add constraint subcategory_filter_fk foreign key (subcategory_id) references public.subcategories
alter table if exists public.specification_sections add constraint product_spec_section_fk foreign key (product_id) references public.products
alter table if exists public.stock_staffs add constraint stock_staff_fk foreign key (stock_id) references public.stocks
alter table if exists public.subcategories add constraint subcategory_category_fk foreign key (category_id) references public.categories
alter table if exists product_images add constraint images_product_fk foreign key (product_id) references public.products
alter table if exists products_criteria add constraint criteria_products_fk foreign key (criteria_id) references public.products
alter table if exists products_criteria add constraint products_criteria_fk foreign key (product_id) references public.criteria
alter table if exists spec_section_specifications add constraint specification_spec_section_fk foreign key (specification_id) references public.specification_sections
alter table if exists spec_section_specifications add constraint spec_section_specification_fk foreign key (spec_section_id) references public.specification
alter table if exists stocks_quantity add constraint product_stock_quantity_fk foreign key (product_id) references public.products
alter table if exists stocks_quantity add constraint stock_quantity_product_fk foreign key (stock_id) references public.stocks
alter table if exists stock_staff_phones add constraint stock_staff_phones_fk foreign key (stock_staff_id) references public.stock_staffs
