create table public.accounts
(
    id uuid not null,
    account_name varchar(255),
    account_uri varchar(255) not null,
    address varchar(255) not null,
    city varchar(255) not null,
    consumer_key varchar(255) not null,
    create_at timestamp not null,
    cvc int4 not null,
    exp_month varchar(255) not null,
    exp_year varchar(255) not null,
    first_name varchar(255) not null,
    identifier varchar(255) not null,
    key_alias varchar(255) not null,
    key_password varchar(255) not null,
    last_name varchar(255) not null,
    partner_id varchar(255) not null,
    post_code int4 not null,
    private_key varchar(255) not null,
    status varchar(255),
    update_at timestamp not null,
    uri_scheme varchar(255) not null,
    primary key (id)
);

create table public.transactions
(
    id int8 generated by default as identity,
    address varchar(255) not null,
    amount numeric(19, 2) not null,
    bill_id int8 not null,
    city varchar(255) not null,
    country varchar(255) not null,
    create_at timestamp not null,
    currency varchar(255) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    payment_type varchar(255) not null,
    status varchar(255),
    transfer_reference varchar(255) not null,
    update_at timestamp not null,
    account_id uuid,
    transaction_id uuid,
    primary key (id)
);

alter table if exists public.accounts drop constraint if exists accounts_account_name_uk;

alter table if exists public.accounts add constraint accounts_account_name_uk unique (account_name);

alter table if exists public.accounts drop constraint if exists accounts_account_uri_uk;

alter table if exists public.accounts add constraint accounts_account_uri_uk unique (account_uri);

alter table if exists public.accounts drop constraint if exists accounts_consumer_key_uk;

alter table if exists public.accounts add constraint accounts_consumer_key_uk unique (consumer_key);

alter table if exists public.accounts drop constraint if exists accounts_key_alias_uk;

alter table if exists public.accounts add constraint accounts_key_alias_uk unique (key_alias);

alter table if exists public.accounts drop constraint if exists accounts_key_password_uk;

alter table if exists public.accounts add constraint accounts_key_password_uk unique (key_password);

alter table if exists public.accounts drop constraint if exists accounts_partner_id_uk;

alter table if exists public.accounts add constraint accounts_partner_id_uk unique (partner_id);

alter table if exists public.accounts drop constraint if exists accounts_private_key_uk;

alter table if exists public.accounts add constraint accounts_private_key_uk unique (private_key);

alter table if exists public.transactions drop constraint if exists transactions_bill_id_uk;

alter table if exists public.transactions add constraint transactions_bill_id_uk unique (bill_id);

alter table if exists public.transactions drop constraint if exists transactions_transfer_reference_uk;

alter table if exists public.transactions add constraint transactions_transfer_reference_uk unique (transfer_reference);

alter table if exists public.transactions add constraint transactions_accounts_fk foreign key (account_id) references public.accounts;

alter table if exists public.transactions add constraint accounts_transactions_fk foreign key (transaction_id) references public.accounts;
