create table public.banners
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    image varchar(255) not null,
    status varchar(255),
    update_at timestamp not null,
    primary key (id)
);

create table public.carousel_image
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    image varchar(255) not null,
    status varchar(255),
    update_at timestamp not null,
    primary key (id)
);
