create table public.accounts
(
    id int8 generated by default as identity,
    address varchar(255) not null,
    create_at timestamp not null,
    currency_balance numeric(19, 2) not null,
    private_key numeric(128, 0) not null,
    public_key numeric(192, 0) not null,
    status varchar(255) not null,
    update_at timestamp not null,
    user_id uuid not null,
    primary key (id)
);

create table public.blocks
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    number int8 not null,
    status varchar(255),
    update_at timestamp not null,
    primary key (id)
);

create table public.contracts_tab
(
    id int8 generated by default as identity,
    address varchar(255) not null,
    create_at timestamp not null,
    full_name varchar(255) not null,
    name varchar(255) not null,
    pow int4 not null,
    status varchar(255),
    update_at timestamp not null,
    primary key (id)
);

create table public.currency
(
    id int8 generated by default as identity,
    address_regex varchar(255) not null,
    create_at timestamp not null,
    full_name varchar(255) not null,
    name varchar(255) not null,
    pow int4 not null,
    status varchar(255),
    update_at timestamp not null,
    primary key (id)
);

create table public.fees
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    fee numeric(19, 2) not null,
    gas_price numeric(19, 2) not null,
    status varchar(255),
    update_at timestamp not null,
    primary key (id)
);

create table public.transactions_tab
(
    id int8 generated by default as identity,
    block_hash varchar(255),
    block_number numeric(19, 2),
    create_at timestamp not null,
    fee numeric(19, 2) not null,
    address_from varchar(255) not null,
    gas_limit numeric(19, 2) not null,
    gas_price numeric(19, 2) not null,
    hash varchar(255) not null,
    nonce numeric(19, 2) not null,
    status varchar(255),
    address_to varchar(255) not null,
    type varchar(255),
    update_at timestamp not null,
    value numeric(19, 2) not null,
    contract_id int8,
    transaction_id int8,
    primary key (id)
);

alter table if exists public.accounts drop constraint if exists accounts_address_uk;

alter table if exists public.accounts add constraint accounts_address_uk unique (address);

alter table if exists public.accounts drop constraint if exists accounts_private_key_uk;

alter table if exists public.accounts add constraint accounts_private_key_uk unique (private_key);

alter table if exists public.accounts drop constraint if exists accounts_public_key_uk;

alter table if exists public.accounts add constraint accounts_public_key_uk unique (public_key);

create table account_contract_balance (account_id int8 not null, contract_balance numeric(19, 2), contract_balance_key varchar(255) not null, primary key (account_id, contract_balance_key));

alter table if exists public.transactions_tab add constraint transactions_tab_contracts_tab_fk foreign key (contract_id) references public.contracts_tab;

alter table if exists public.transactions_tab add constraint accounts_transactions_fk foreign key (transaction_id) references public.accounts;

alter table if exists account_contract_balance add constraint account_contract_balance_accounts_fk foreign key (account_id) references public.accounts;
