create table public.order_details
(
    id int8 generated by default as identity,
    amount DECIMAL(8, 4) not null,
    city varchar(255) not null,
    company varchar(255) not null,
    country varchar(255) not null,
    create_at timestamp not null,
    customer_id int8 not null,
    delivery_amount DECIMAL(8, 4) not null,
    delivery_data varchar(255) not null,
    flat_number varchar(255) not null,
    region varchar(255) not null,
    staff_id int8, status varchar(255),
    street varchar(255) not null,
    street_number varchar(255) not null,
    update_at timestamp not null,
    user_id uuid not null,
    weight DECIMAL(8, 4) not null,
    zip_code varchar(255) not null,
    primary key (id)
)

create table public.order_items
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    discount numeric(19, 2) not null,
    price numeric(19, 2) not null,
    product_id int8 not null,
    quantity int4 not null,
    status varchar(255),
    update_at timestamp not null,
    order_item_id int8 not null,
    primary key (id)
)

alter table if exists public.order_items add constraint orders_order_item_fk foreign key (order_item_id) references public.order_details
