server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-properties
          searchPaths:
            - '{application}/{profile}'
            - '/global/{profile}'
            - '/keystore/{profile}'
jwt:
  keys:
    store:
      enabled: false