create table public.addresses
(
    id int8 generated by default as identity,
    city varchar(128) not null,
    country varchar(128) not null,
    create_at timestamp not null,
    flat_number varchar(50),
    region varchar(128),
    status varchar(255),
    street varchar(128) not null,
    street_number varchar(128) not null,
    update_at timestamp not null,
    zip_code varchar(255) not null,
    primary key (id)
);

create table public.customer_statistics
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    returned_orders int4 not null,
    status varchar(255),
    success_orders int4 not null,
    total_orders int4 not null,
    update_at timestamp not null,
    customer_id int8 not null,
    primary key (id)
);

create table public.customers
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    customer_email varchar(128) not null,
    customer_phone varchar(128) not null,
    first_name varchar(150) not null,
    last_name varchar(150) not null,
    status varchar(255),
    update_at timestamp not null,
    user_id uuid not null,
    address_id int8,
    primary key (id)
);

create index customer_user_id_idx on public.customers (user_id);

alter table if exists public.customers drop constraint if exists uk_customer_user_id;

alter table if exists public.customers add constraint uk_customer_user_id unique (user_id);

alter table if exists public.customer_statistics add constraint customer_stat_customer_fk foreign key (customer_id) references public.customers;

alter table if exists public.customers add constraint customer_address_fk foreign key (address_id) references public.addresses;
