create table public.accounts
(
    id int8 generated by default as identity,
    amount numeric(19, 2) not null,
    chain_code varchar(255) not null,
    create_at timestamp not null,
    mnemonic varchar(255) not null,
    private_key varchar(255) not null,
    public_key varchar(255) not null,
    status varchar(255) not null,
    time_stamp int8 not null,
    update_at timestamp not null,
    user_id uuid not null,
    primary key (id)
);

create table public.addresses
(
    id int8 generated by default as identity,
    address varchar(255) not null,
    amount numeric(19, 2) not null,
    create_at timestamp not null,
    index int4 not null,
    status varchar(255) not null,
    update_at timestamp not null,
    account_id int8,
    address_id int8,
    primary key (id)
);

create table public.blocks
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    number int8 not null,
    status varchar(255) not null,
    update_at timestamp not null,
    primary key (id)
);

create table public.currency
(
    id int8 generated by default as identity,
    address_regex varchar(255) not null,
    create_at timestamp not null,
    full_name varchar(255) not null,
    name varchar(255) not null,
    pow int4 not null,
    status varchar(255) not null,
    update_at timestamp not null,
    primary key (id)
);

create table public.fee_per_kb
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    fee numeric(19, 2) not null,
    status varchar(255),
    update_at timestamp not null,
    primary key (id)
);

create table public.transactions
(
    id int8 generated by default as identity,
    block_hash varchar(255) not null,
    block_height int8 not null,
    confirmations int4 not null,
    create_at timestamp not null,
    hash varchar(255) not null,
    status varchar(255) not null,
    type varchar(255) not null,
    update_at timestamp not null,
    value numeric(19, 2) not null,
    transaction_id int8,
    primary key (id)
);

create table public.trial_transaction
(
    id int8 generated by default as identity,
    change numeric(19, 2) not null,
    create_at timestamp not null,
    fee numeric(19, 2) not null,
    address_from varchar(255) not null,
    hash varchar(255) not null,
    signed_trx varchar(255) not null,
    status varchar(255) not null,
    address_to varchar(255) not null,
    update_at timestamp not null,
    value numeric(19, 2) not null,
    primary key (id)
);

create table public.unspent_outputs
(
    id int8 generated by default as identity,
    create_at timestamp not null,
    index int4 not null,
    pub_key_hash varchar(255) not null,
    script varchar(255) not null,
    status varchar(255) not null,
    trx_hash varchar(255) not null,
    update_at timestamp not null,
    value numeric(19, 2) not null,
    out_id int8,
    outs_id int8,
    primary key (id)
);

alter table if exists public.accounts drop constraint if exists accounts_chain_code_uk;

alter table if exists public.accounts add constraint accounts_chain_code_uk unique (chain_code);

alter table if exists public.accounts drop constraint if exists accounts_mnemonic_uk;

alter table if exists public.accounts add constraint accounts_mnemonic_uk unique (mnemonic);

alter table if exists public.accounts drop constraint if exists accounts_private_key_uk;

alter table if exists public.accounts add constraint accounts_private_key_uk unique (private_key);

alter table if exists public.accounts drop constraint if exists accounts_public_key_uk;

alter table if exists public.accounts add constraint accounts_public_key_uk unique (public_key);

alter table if exists public.accounts drop constraint if exists accounts_time_stamp_uk;

alter table if exists public.accounts add constraint accounts_time_stamp_uk unique (time_stamp);

alter table if exists public.addresses drop constraint if exists addresses_address_uk;

alter table if exists public.addresses add constraint addresses_address_uk unique (address);

alter table if exists public.addresses drop constraint if exists addresses_index_uk;

alter table if exists public.addresses add constraint addresses_index_uk unique (index);

create table transaction_inputs (transaction_id int8 not null, inputs varchar(255));

create table transaction_outputs (transaction_id int8 not null, outputs varchar(255));

alter table if exists public.addresses add constraint addresses_accounts_fk foreign key (account_id) references public.accounts;

alter table if exists public.addresses add constraint account_address_fk foreign key (address_id) references public.accounts;

alter table if exists public.transactions add constraint account_transaction_fk foreign key (transaction_id) references public.accounts;

alter table if exists public.unspent_outputs add constraint trial_trx_unspent_out foreign key (out_id) references public.trial_transaction;

alter table if exists public.unspent_outputs add constraint transaction_outs_fk foreign key (outs_id) references public.addresses;

alter table if exists transaction_inputs add constraint transaction_inputs_transactions_fk foreign key (transaction_id) references public.transactions;

alter table if exists transaction_outputs add constraint transaction_outputs_transactions_fk foreign key (transaction_id) references public.transactions
